import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { Navbar } from "~/components/Navbar";
import { api } from "~/utils/api";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Codebook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
      </main>
    </>
  );
};

export default Home;

