import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { Navbar } from "~/components/Navbar";
import { RouterOutputs, api } from "~/utils/api";
import { useState } from "react";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Codebook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Content />
      </main>
    </>
  );
};

export default Home;
type Subject = RouterOutputs["subject"]["getAll"][0];
const Content: React.FC = () => {

  const { data: sessionData } = useSession();

  const [selectedSubject, setSelectedSubject] = useState<Subject | null>(null);

  const { data: subjects, refetch: refetchSubjects } = api.subject.getAll.useQuery(
    undefined, // no input
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => {
        setSelectedSubject(selectedSubject ?? data[0] ?? null);
      },
    }
  );

  const createSubject = api.subject.create.useMutation({
    onSuccess: () => {
      void refetchSubjects();
    },
  });



  return(
    
    <div className="mx-5 mt-5 grid grid-cols-4 gap-2">
      {sessionData?.user ? (
      <div className="px-2">
        <div className=" grid grid-rows-2 gap-2">
        <input
          type="text"
          placeholder="New Subject"
          className="input-bordered input w-full"
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              createSubject.mutate({
                title: e.currentTarget.value,
              });
              e.currentTarget.value = "";
            }
          }}
        />
        <div className="btn"

        >
          Add Subject

        </div>
        </div>
        <div className="divider"></div>
        <ul className="menu rounded-box w-56 bg-base-100 p-1">
          {subjects?.map((subject) => (
            <li key={subject.id}>
              <a
                href="#"
                onClick={(evt) => {
                  evt.preventDefault();
                  setSelectedSubject(subject);
                }}
              >
                {subject.title}
              </a>
            </li>
          ))}
        </ul>
        

      </div>
      ) : ( ""

      )}
      </div>
    


  )

}